export const MockData = [
  {
    created: 1563973005000,
    duration: 5400000,
    id: '263418506',
    name: 'TechNet Beer & Bytes',
    date_in_series_pattern: false,
    status: 'upcoming',
    time: 1566423000000,
    local_date: '2019-08-21',
    local_time: '17:30',
    updated: 1564584211000,
    utc_offset: -14400000,
    waitlist_count: 0,
    yes_rsvp_count: 22,
    venue: {
      id: 25933293,
      name: 'theClubhou.se @ Georgia Cyber Center',
      lat: 33.47985076904297,
      lon: -81.9701156616211,
      repinned: true,
      address_1: 'One 11th St.',
      address_2: 'Suite 3700',
      city: 'Augusta',
      country: 'us',
      localized_country_name: 'USA',
      zip: '30901',
      state: 'ga'
    },
    group: {
      created: 1341289766000,
      name: 'Hack Augusta',
      id: 4220332,
      join_mode: 'open',
      lat: 33.459999084472656,
      lon: -81.97000122070312,
      urlname: 'HackAugusta',
      who: 'Awesome people',
      localized_location: 'Augusta, GA',
      state: 'GA',
      country: 'us',
      region: 'en_US',
      timezone: 'US/Eastern'
    },
    link: 'https://www.meetup.com/HackAugusta/events/263418506/',
    description: '<p>Join theClubhou.se, IntelliGenesis, and Uniti Fiber during AFCEA TechNet Week for networking opportunities, tours, and demonstrations of innovative technology.</p> <p>The IntelliGenesis team will provide an overview of their Cybersecurity services to include Digital Forensics Examination, Drone Forensics and ICS/SCADA Cyber Defense training. Additionally, they will provide a demonstration of tools and programs utilized in their Critical Infrastructure and Control System Cybersecurity Course.</p> <p>We\'ll be on the rooftop patio of the Georgia Cyber Center\'s Hull-McKnight building!</p> ',
    how_to_find_us: 'We will meet on the rooftop! Take the furthest to the left elevator of the Hull McKnight building of the Georgia Cyber Center.',
    visibility: 'public',
    member_pay_fee: false
  },
  {
    created: 1562853457000,
    duration: 3600000,
    id: '263062144',
    name: 'Agile Augusta: Does Your Team Groove? What You Can Learn from a Bass Player!',
    date_in_series_pattern: false,
    status: 'upcoming',
    time: 1566943200000,
    local_date: '2019-08-27',
    local_time: '18:00',
    updated: 1564662843000,
    utc_offset: -14400000,
    waitlist_count: 0,
    yes_rsvp_count: 4,
    venue: {
      id: 25933293,
      name: 'theClubhou.se @ Georgia Cyber Center',
      lat: 33.47987747192383,
      lon: -81.97005462646484,
      repinned: true,
      address_1: 'One 11th St.',
      address_2: 'Suite 3700',
      city: 'Augusta',
      country: 'us',
      localized_country_name: 'USA',
      zip: '30901',
      state: 'ga'
    },
    group: {
      created: 1341289766000,
      name: 'Hack Augusta',
      id: 4220332,
      join_mode: 'open',
      lat: 33.459999084472656,
      lon: -81.97000122070312,
      urlname: 'HackAugusta',
      who: 'Awesome people',
      localized_location: 'Augusta, GA',
      state: 'GA',
      country: 'us',
      region: 'en_US',
      timezone: 'US/Eastern'
    },
    link: 'https://www.meetup.com/HackAugusta/events/263062144/',
    description: '<p>If your team made music, what would it sound like? Would it be closer to a loud, unrefined, but enthusiastic garage band or a beautiful, precise, well-orchestrated symphony?</p> <p>Your Agile team has more in common with a band than you may realize. I didn’t initially see the connections, but as I became a better bass player, I became a better Scrum Master and vice versa.</p> <p>You don’t need to play an instrument or be a great singer to be musical. Longfellow called music the “universal language of mankind” and everyone enjoys music in some shape, form, or fashion.</p> <p>This session is for anyone who is interested in expanding their connection to music and using that knowledge to create unique connections with colleagues and team members. Please join me and experience how space, dissonance, and groove can be applied to your teams and organizations.</p> <p>This month\'s speaker will be David Gentry.</p> <p>Credits: 1 PDU (PMP and PMI-ACP), 1 SEU</p> <p>Beverages and light refreshments will be provided. If you have any questions, please contact David Gentry at [masked]</p> ',
    how_to_find_us: 'At the new Cyber Center, 3rd floor, turn left out of the elevators!',
    visibility: 'public',
    member_pay_fee: false
  },
  {
    created: 1563539503000,
    duration: 3600000,
    id: '263285296',
    name: 'Lunch & Learn with SME CPAs: What is accounting anyway?',
    date_in_series_pattern: false,
    status: 'upcoming',
    time: 1570636800000,
    local_date: '2019-10-09',
    local_time: '12:00',
    updated: 1563554697000,
    utc_offset: -14400000,
    waitlist_count: 0,
    yes_rsvp_count: 5,
    venue: {
      id: 25933293,
      name: 'theClubhou.se @ Georgia Cyber Center',
      lat: 33.47986602783203,
      lon: -81.97001647949219,
      repinned: true,
      address_1: 'One 11th St.',
      address_2: 'Suite 3700',
      city: 'Augusta',
      country: 'us',
      localized_country_name: 'USA',
      zip: '30901',
      state: 'ga'
    },
    group: {
      created: 1341289766000,
      name: 'Hack Augusta',
      id: 4220332,
      join_mode: 'open',
      lat: 33.459999084472656,
      lon: -81.97000122070312,
      urlname: 'HackAugusta',
      who: 'Awesome people',
      localized_location: 'Augusta, GA',
      state: 'GA',
      country: 'us',
      region: 'en_US',
      timezone: 'US/Eastern'
    },
    link: 'https://www.meetup.com/HackAugusta/events/263285296/',
    description: '<p>Every business and every individual needs to have some kind of accounting system in their lives. Otherwise, finances can get away from you, you don’t know what you’ve spent, or whether you can expect a profit or a loss from their business. If you’re smart, staying on top of accounting for your business or for your personal checking account is a necessary activity on a daily basis.</p> <p>As boring as it sounds, accounting by definition is the language of business. Looking at a set of good financials can tell you almost everything about a business across any industry. It is a vital and critical part of running and operating a successful company, especially for those that are growing.</p> <p>Our presenter is Brandon Barton, CPA. Brandon is a CPA with a MACC from Kennesaw State University. After interning and working for a year in Atlanta, he is now back in his hometown of Augusta working as a tax staff accountant for SME CPAs. He has been with SME since December 2017.</p> <p>Lunch is provided!</p> ',
    how_to_find_us: 'Third floor of the new Cyber Center\'s Hull McKnight building',
    visibility: 'public',
    member_pay_fee: false
  },
  
]

// export const MockLocations = [
    
//         {
//             city: 'Munich',
//             country: 'de',
//             localized_country_name: 'Germany',
//             name_string: 'Munich, Germany',
//             zip: 'meetup3',
//             lat: 48.14,
//             lon: 11.58,
//           },
//           {
//             city: 'Munich',
//             country: 'us',
//             localized_country_name: 'USA',
//             state: 'ND',
//             name_string: 'Munich, North Dakota, USA',
//             zip: '58352',
//             lat: 48.66,
//             lon: -98.85,
//           }
    
// ] 
