const mockData = {
  city: {
    id: 80201,
    city: 'Denver',
    lat: 39.7,
    lon: -105.08,
    state: 'CO',
    country: 'us',
    zip: '80201',
    member_count: 48435
  },
  events: [
    {
      created: 1558282293000,
      duration: 10800000,
      id: '261592813',
      name: 'New & Returning Members Night',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1567468800000,
      local_date: '2019-11-02',
      local_time: '18:00',
      updated: 1560897088000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 16,
      venue: {
        id: 9942932,
        name: 'Galvanize',
        lat: 39.73353576660156,
        lon: -104.99261474609375,
        repinned: true,
        address_1: '1062 Delaware Street',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80204',
        state: 'CO'
      },
      group: {
        created: 1354586857000,
        name: 'Code for Denver',
        id: 6104442,
        join_mode: 'open',
        lat: 39.72999954223633,
        lon: -104.94999694824219,
        urlname: 'CodeForDenver',
        who: 'Civic Innovators',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/CodeForDenver/events/261592813/',
      description: '<p>New &amp; Returning Members Night is where we welcome any new members to Code for Denver and where any returning members can continue working with their team on projects.</p> <p>If you’re a new member, or curious about joining Code for Denver, there will be an onboarding session at this night. If you want to get a head start, follow our self onboarding below.</p> <p>You can learn more about Code for Denver, including our open projects, at www.codefordenver.org.<br/>∙<br/>∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙♦♦♦∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙<br/>∙<br/>CODE OF CONDUCT<br/>──────────────<br/>Code for Denver is a safe place to gather, free from harassment and everyone is welcome who embraces diversity, a culture of learning, and is respectful of others and their opinions.</p> <p>This event follows Code for Denver’s Code of Conduct, please read it before attending.</p> <p>If you have any concerns, please contact [masked]<br/>∙<br/>∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙♦♦♦∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙<br/>∙<br/>FAQ<br/>───<br/>There is a full FAQ posted on our GitHub, but here are some highlights we think are important.</p> <p>Where is Galvanize, and where do I park?<br/>--------------------------------------------------<br/>Galvanize is at 1062 Delaware St. on the corner of W 11th Ave and Delaware Street in the Golden Triangle neighborhood of Denver.</p> <p>There’s ample street parking all around, both 2 hour and metered parking should be free of charge and time limit during our meetings. Galvanize is marked by the red pin, and dark grey box.</p> <p>What do I need to bring to my first meetup?<br/>--------------------------------------------------<br/>We will have you create some accounts both on our site and for the technology we use, so a laptop or a smartphone will be useful.</p> <p>I\'m a beginner programmer. Can I still get involved?<br/>--------------------------------------------------<br/>Yes! Many of our members have been beginning programmers who have found the environment helpful to improve their abilities while also working on real world problems and providing value.</p> <p>I\'m not a programmer or interested in programming. Can I still get involved?<br/>--------------------------------------------------<br/>Yes! Helping solve challenges in the community takes more than programming expertise. Our brigade volunteers also have backgrounds in marketing, design, sales, facilitation, nonprofits, project management, and more. Additional perspectives and experiences are always valued and welcome.</p> <p>What is Code for Denver current working on?<br/>--------------------------------------------------<br/>We have multiple teams working on many different projects at completely different stages. You can find the list, including general descriptions, status, skills needed, and more at our Current Projects page on the website.</p> <p>Who can I contact for additional questions?<br/>--------------------------------------------------<br/>Get in touch with our organizers via our Meetup site or drop us a line at [masked]<br/>∙<br/>∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙♦♦♦∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙<br/>∙<br/>USEFUL LINKS<br/>──────────<br/>► ',
      how_to_find_us: 'There is generally a sign pointing out which room we are in. If you can\'t find us, ask the Galvanize front desk.',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    },
    {
      created: 1512747817000,
      duration: 10800000,
      id: 'cxnkgryzlbrb',
      name: 'August Develop Happy Hour',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1565913600000,
      local_date: '2019-10-20',
      local_time: '18:00',
      updated: 1565378564000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 100,
      venue: {
        id: 26226878,
        name: 'Big Trouble',
        lat: 39.76924133300781,
        lon: -104.977294921875,
        repinned: false,
        address_1: '3501 Wazee St Suite #100',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80216',
        state: 'CO'
      },
      group: {
        created: 1439225694000,
        name: 'Develop Happy Hour',
        id: 18819666,
        join_mode: 'open',
        lat: 39.900001525878906,
        lon: -104.94999694824219,
        urlname: 'Develop-Happy-Hour',
        who: 'Cultivators',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/Develop-Happy-Hour/events/cxnkgryzlbrb/',
      description: '<p>August will be a special edition! We\'ll be merging with the DVLP DNVR 2019 conference Opening Happy Hour to become the ultimate power of happy hours! Don\'t worry no conference badge is required. Come mingle hear about what people learned at the conference and make connections.</p> <p>Come hang out with fellow members of the growing Denver/Boulder tech scene. Everyone is welcome. Come to learn, make contacts or discuss your latest project. No speaker, no agenda, no code knowledge necessary, just drinks.</p> <p>Monthly Happy Hour. We are always open to suggestions for new venues to host the happy hour. Please feel free to message the us with any ideas.</p> ',
      how_to_find_us: 'We\'ll be at Big Trouble, the bar on the second floor in the middle of the Zeppelin Station food hall.',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1560289420000,
      duration: 3600000,
      id: 'tnvdcryzlbkc',
      name: 'Technology Partners Lunch',
      rsvp_limit: 25,
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1566928800000,
      local_date: '2019-10-27',
      local_time: '12:00',
      rsvp_close_offset: 'PT1M',
      updated: 1560289420000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 7,
      venue: {
        id: 26038353,
        name: 'Tap & Burger Belleview Station',
        lat: 39.62522888183594,
        lon: -104.90689849853516,
        repinned: true,
        address_1: '4910 S Newport St',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80237',
        state: 'co'
      },
      group: {
        created: 1543356603000,
        name: 'Technology Partners Business Networking',
        id: 30606504,
        join_mode: 'open',
        lat: 39.650001525878906,
        lon: -104.9800033569336,
        urlname: 'Technology-Partners-Business-Networking',
        who: 'Members',
        localized_location: 'Englewood, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/Technology-Partners-Business-Networking/events/tnvdcryzlbkc/',
      description: '<p>Join us for lunch, introductions, and some great conversation with like-minded digital technology businesses.</p> <p>Typical Agenda:<br/>* Come early for extra networking time.<br/>* Start promptly at 12:05 - please arrive early<br/>* Introductions - Who you are and your technical specialty<br/>* Topic of the Day - This could be sharing more about our individual businesses, round table topics, or a presentation by Consortium Members.<br/>* Pass contact information - bring business cards!<br/>* End at 1:00<br/>* Stay longer and network if your schedule allows</p> <p>While we do not charge for this event, we do ask that you please make a purchase out of respect for our gracious hosts at Tap and Grill. Please let us know if you RSVP\'d and can\'t make it so we have a correct count for the restaurant.</p> ',
      how_to_find_us: 'In the private room in the back!',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1548175893000,
      duration: 10800000,
      id: 'lsbxxqyzlbsb',
      name: 'Pitch Lab: How To Tell A Captivating Story Like A Stand-Up Comedian!',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1565829000000,
      local_date: '2019-11-14',
      local_time: '18:30',
      updated: 1563204813000,
      utc_offset: -21600000,
      waitlist_count: 0,
      yes_rsvp_count: 31,
      venue: {
        id: 9942932,
        name: 'Galvanize',
        lat: 39.73353576660156,
        lon: -104.99261474609375,
        repinned: true,
        address_1: '1062 Delaware Street',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80204',
        state: 'CO'
      },
      group: {
        created: 1215822969000,
        name: 'Refresh Denver',
        id: 1220063,
        join_mode: 'open',
        lat: 39.75,
        lon: -104.98999786376953,
        urlname: 'refreshdenver',
        who: 'Designers & Developers',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/refreshdenver/events/lsbxxqyzlbsb/',
      description: '<p>About This Workshop</p> <p>Learn to be a more engaging storyteller using proven techniques from your favorite comedians like John Mulaney, Tig Notaro, and Dave Chappelle.</p> <p>In this workshop, we’ll dive into the essential elements of telling a great story and how to avoid common pitfalls that make most stories fall flat.</p> <p>Takeaways from the Stage</p> <p>Storytelling framework to understand why stories work and how to improve yours<br/>The importance of authenticity and vulnerability to tell better stories<br/>Why conflict is the secret sauce to keeping an audience interested</p> <p>About Your Instructor</p> <p>Jay Mays is a 20-year sales veteran and stand-up comedy producer. From his underdog beginnings in dive bars to being awarded Best Comedy Venue in Miami, Jay has produced live comedy events for some of the biggest names in entertainment including Viacom, TEDx &amp; Live Nation.</p> <p>As Managing Partner at Pitch Lab, Jay combines the seemingly disparate worlds of sales and comedy to help professionals be more confident, engaging speakers.</p> <p>Schedule<br/>6:30PM - Drinks &amp; Camaraderie<br/>7:00PM - Talk</p> ',
      how_to_find_us: 'Follow signs for Refresh Denver once inside Galvanize Golden Triangle',
      visibility: 'public',
      member_pay_fee: false
    },
    {
      created: 1558282350000,
      duration: 10800000,
      id: 'kgwncryzpbgb',
      name: 'New & Returning Members Night',
      date_in_series_pattern: false,
      status: 'upcoming',
      time: 1572915600000,
      local_date: '2019-11-04',
      local_time: '18:00',
      updated: 1560896911000,
      utc_offset: -25200000,
      waitlist_count: 0,
      yes_rsvp_count: 3,
      venue: {
        id: 9942932,
        name: 'Galvanize',
        lat: 39.73353576660156,
        lon: -104.99261474609375,
        repinned: true,
        address_1: '1062 Delaware Street',
        city: 'Denver',
        country: 'us',
        localized_country_name: 'USA',
        zip: '80204',
        state: 'CO'
      },
      group: {
        created: 1354586857000,
        name: 'Code for Denver',
        id: 6104442,
        join_mode: 'open',
        lat: 39.72999954223633,
        lon: -104.94999694824219,
        urlname: 'CodeForDenver',
        who: 'Civic Innovators',
        localized_location: 'Denver, CO',
        state: 'CO',
        country: 'us',
        region: 'en_US',
        timezone: 'US/Mountain'
      },
      link: 'https://www.meetup.com/CodeForDenver/events/kgwncryzpbgb/',
      description: '<p>New &amp; Returning Members Night is where we welcome any new members to Code for Denver and where any returning members can continue working with their team on projects.</p> <p>If you’re a new member, or curious about joining Code for Denver, there will be an onboarding session at this night. If you want to get a head start, follow our self onboarding below.</p> <p>You can learn more about Code for Denver, including our open projects, at www.codefordenver.org.<br/>∙<br/>∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙♦♦♦∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙<br/>∙<br/>CODE OF CONDUCT<br/>──────────────<br/>Code for Denver is a safe place to gather, free from harassment and everyone is welcome who embraces diversity, a culture of learning, and is respectful of others and their opinions.</p> <p>This event follows Code for Denver’s Code of Conduct, please read it before attending.</p> <p>If you have any concerns, please contact [masked]<br/>∙<br/>∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙♦♦♦∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙<br/>∙<br/>FAQ<br/>───<br/>There is a full FAQ posted on our GitHub, but here are some highlights we think are important.</p> <p>Where is Galvanize, and where do I park?<br/>--------------------------------------------------<br/>Galvanize is at 1062 Delaware St. on the corner of W 11th Ave and Delaware Street in the Golden Triangle neighborhood of Denver.</p> <p>There’s ample street parking all around, both 2 hour and metered parking should be free of charge and time limit during our meetings. Galvanize is marked by the red pin, and dark grey box.</p> <p>What do I need to bring to my first meetup?<br/>--------------------------------------------------<br/>We will have you create some accounts both on our site and for the technology we use, so a laptop or a smartphone will be useful.</p> <p>I\'m a beginner programmer. Can I still get involved?<br/>--------------------------------------------------<br/>Yes! Many of our members have been beginning programmers who have found the environment helpful to improve their abilities while also working on real world problems and providing value.</p> <p>I\'m not a programmer or interested in programming. Can I still get involved?<br/>--------------------------------------------------<br/>Yes! Helping solve challenges in the community takes more than programming expertise. Our brigade volunteers also have backgrounds in marketing, design, sales, facilitation, nonprofits, project management, and more. Additional perspectives and experiences are always valued and welcome.</p> <p>What is Code for Denver current working on?<br/>--------------------------------------------------<br/>We have multiple teams working on many different projects at completely different stages. You can find the list, including general descriptions, status, skills needed, and more at our Current Projects page on the website.</p> <p>Who can I contact for additional questions?<br/>--------------------------------------------------<br/>Get in touch with our organizers via our Meetup site or drop us a line at [masked]<br/>∙<br/>∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙♦♦♦∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙<br/>∙<br/>USEFUL LINKS<br/>──────────<br/>► ',
      how_to_find_us: 'There is generally a sign pointing out which room we are in. If you can\'t find us, ask the Galvanize front desk.',
      visibility: 'public',
      pro_is_email_shared: false,
      member_pay_fee: false
    }
  ]
}

export { mockData }